#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd
#script only displays:
#username
#user id
#home directory path for the user

while read -r line; do
echo "$line" | cut -d':' -f 1,3,6
done < /etc/passwd
