#!/usr/bin/env bash
#script that displays: the content of the current directory in a list format where onyl the part of the name after the first dash is displayed
for x in *
do
echo "$x" | cut -f 2- -d '-'
done
